### ISSUE TITLE
adding scripts to scripts files

### ISSUE THREAD

**Issue by laurenechan** [laurenechan/MB599#4]
For the sake of fun, I thought I'd show you all how the github issue tracker works. This uses markdown style formatting and allows you to communicate in a long chain of comments and also put in images, task completion trackers and assign people to things as well as indicate labels such as "question" or "bug" that get color coded for easy navigation. 
We need to add scripts to our scripts file including:
- [ ] trim
- [ ] align
- [ ] dif expression
- [ ] stats scripts

@bribrihead @hansonch @mkenglish

**Comment by laurenechan** [comment]
@bribrihead can you upload the final genome generation script to its own file? I've made you a blank one to put it in

**Comment by bribrihead** [comment]
Done!
